management:
    security:
        enabled: false
security:
    basic:
        enabled: false
spring:
    autoconfigure:
        exclude:
        - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
    profiles:
        active: prod
    session:
        jdbc:
            initialize-schema: always
