version: 0.2
spring:
  session:
    jdbc:
      initialize-schema: always
  datasource:
    username: root
    url: jdbc:mysql://endoaws.cfc5eajyvbwx.us-east-2.rds.amazonaws.com:3306/endoAWS?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&serverTimezone=UTC
    password: shadowdancer6653!6
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  profiles:
    active: prod
management:
  security:
    enabled: "false"
security:
  basic:
    enabled: "false"
server:
  port: "5000"
phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
      - echo In the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
      - mv target/endo-server-0.0.1-SNAPSHOT.jar endo-server-0.0.1-SNAPSHOT.jar
artifacts:
  files:
    - endo-server-0.0.1-SNAPSHOT.jar
    - .ebextensions/**/*
