apiVersion: apps/v1
kind: Deployment
metadata:
  name: endo-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: endo-server
      tier: backend
  template:
    metadata: 
      labels:
        app: endo-server
        tier: backend
    spec: 
      containers:
        - name: endo-server-java
          image: vagtsop/endo-endo-server-container:latest
          ports:
          - containerPort: 8080
          env:  
            - name: SPRING.DATASOURCE.URL
              valueFrom: 
                 secretKeyRef:
                   name: secret
                   key: spring.datasource.url
            - name: SPRING.DATASOURCE.USERNAME
              valueFrom: 
                 secretKeyRef:
                   name: secret
                   key: spring.datasource.username
            - name: SPRING.DATASOURCE.PASSWORD
              valueFrom: 
                 secretKeyRef:
                   name: secret
                   key: spring.datasource.password
            - name: JWT.SECRET
              valueFrom: 
                 secretKeyRef:
                   name: secret
                   key: jwt.secret
            - name: FRONT.DOMAIN
              valueFrom: 
                 secretKeyRef:
                   name: secret
                   key: front.domain
            - name: BACK.DOMAIN
              valueFrom: 
                 secretKeyRef:
                   name: secret
                   key: back.domain
            - name: IMAGE.PATH
              valueFrom: 
                 secretKeyRef:
                   name: secret
                   key: image.path
      imagePullSecrets:
        - name: dbsecret
