apiVersion: v1
kind: Secret
metadata:
  name: secret
type: Opaque
stringData:
  spring.datasource.url: jdbc:mysql://mysql/endo?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&serverTimezone=UTC
  spring.datasource.username: root
  spring.datasource.password: root