apiVersion: v1
kind: Service
metadata:
  name: endo-server-service
spec:
  selector: 
    app: endo-server
  ports:
    - protocol: 'TCP'
      port: 8080
      targetPort: 8080
    # - protocol: 'TCP'
    #   port: 443
    #   targetPort: 443
  type: LoadBalancer