spring:
    datasource:
        password: root
        url: jdbc:mysql://localhost:3306/endo?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&serverTimezone=UTC
        username: root
